/*
 * Copyright (C) 2024 ArtInChip Technology Co. Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef AICCONSTS_H
#define AICCONSTS_H

#define AIC_DEFAULT_WIDTH 1024
#define AIC_DEFAULT_HEIGHT 600

#define AIC_STATUS_BAR_WIDTH 1024
#define AIC_STATUS_BAR_HEIGHT 32

#define AIC_NAVIGATION_BAR_WIDTH 1024
#define AIC_NAVIGATION_BAR_HEIGHT 48

#define AIC_CENTRAL_VIEW_WIDTH 1024
#define AIC_CENTRAL_VIEW_HEIGHT 520

#define AIC_CENTRAL_BUTTON_WIDTH 215
#define AIC_CENTRAL_BUTTON_HEIGHT 160
#define AIC_CENTRAL_BUTTON_XMARGIN 48
#define AIC_CENTRAL_BUTTON_YMARGIN 5

#define AIC_PLAY_BUTTON_XMARGIN 480
#define AIC_PLAY_BUTTON_YMARGIN 400

#define AIC_PLAY_BUTTON_WIDTH  64
#define AIC_PLAY_BUTTON_HEIGHT 64

#endif // AICCONSTS_H
