#ifndef AICCONSTS_H
#define AICCONSTS_H

#define AIC_DEFAULT_WIDTH 1024
#define AIC_DEFAULT_HEIGHT 600

#define AIC_STATUS_BAR_WIDTH 1024
#define AIC_STATUS_BAR_HEIGHT 32

#define AIC_NAVIGATION_BAR_WIDTH 1024
#define AIC_NAVIGATION_BAR_HEIGHT 48

#define AIC_CENTRAL_VIEW_WIDTH 1024
#define AIC_CENTRAL_VIEW_HEIGHT 520

#define AIC_CENTRAL_BUTTON_WIDTH 215
#define AIC_CENTRAL_BUTTON_HEIGHT 160
#define AIC_CENTRAL_BUTTON_XMARGIN 48
#define AIC_CENTRAL_BUTTON_YMARGIN 5

#endif // AICCONSTS_H
