AIC_LOGO_VERSION =
AIC_LOGO_ENABLE_TARBALL = NO
AIC_LOGO_ENABLE_PATCH = NO
AIC_LOGO_INSTALL_STAGING = YES

AIC_LOGO_DEPENDENCIES += test-common
AIC_LOGO_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local

define AIC_LOGO_REMOVE_HEADERS_IN_TARGET
	rm -rf $(TARGET_DIR)/usr/local/include/
endef
AIC_LOGO_POST_INSTALL_TARGET_HOOKS += AIC_LOGO_REMOVE_HEADERS_IN_TARGET

$(eval $(cmake-package))

