# SPDX-License-Identifier: GPL-2.0
spinand-objs := core.o gigadevice.o macronix.o micron.o paragon.o toshiba.o
spinand-objs += winbond.o fmsh.o foresee.o zbit.o elite.o esmt.o umtek.o byte.o
obj-$(CONFIG_MTD_SPI_NAND) += spinand.o
obj-$(CONFIG_NAND_BBT_MANAGE) += aic_bbt.o
