#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_GSL168X)	+= oncell_HRT_CE.o
oncell_HRT_CE-objs := touch_gsl1686.o gsl_point_id.o init-input.o

