# SPDX-License-Identifier: GPL-2.0

snd-soc-aic-i2s-objs := aic-i2s.o
obj-$(CONFIG_SND_SOC_AIC_I2S) += snd-soc-aic-i2s.o

snd-soc-aic-ac102-objs := aic-ac102.o
obj-$(CONFIG_SND_SOC_AIC_AC102) += snd-soc-aic-ac102.o

snd-soc-aic-codec-objs := aic-codec-analog.o
obj-$(CONFIG_SND_SOC_AIC_CODEC) += aic-codec-analog.o

snd-soc-aic-codec-objs := aic-codec.o
obj-$(CONFIG_SND_SOC_AIC_CODEC) += snd-soc-aic-codec.o

snd-soc-aic-ac107-objs := aic-ac107.o
obj-$(CONFIG_SND_SOC_AIC_AC107) += snd-soc-aic-ac107.o
