TEST_KEYADC_VERSION =
TEST_KEYADC_ENABLE_TARBALL = NO
TEST_KEYADC_ENABLE_PATCH = NO

TEST_KEYADC_DEPENDENCIES += test-common

TEST_KEYADC_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
