TEST_DMA_BUF_VERSION =
TEST_DMA_BUF_ENABLE_TARBALL = NO
TEST_DMA_BUF_ENABLE_PATCH = NO

TEST_DMA_BUF_DEPENDENCIES += test-common

TEST_DMA_BUF_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
