TEST_UART_VERSION =
TEST_UART_ENABLE_TARBALL = NO
TEST_UART_ENABLE_PATCH = NO

TEST_UART_DEPENDENCIES += test-common

TEST_UART_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
