TEST_GPIO_VERSION =
TEST_GPIO_ENABLE_TARBALL = NO
TEST_GPIO_ENABLE_PATCH = NO

TEST_GPIO_DEPENDENCIES += test-common

TEST_GPIO_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
