# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_AIC_PANE_RGB_GENERAL) += panel_rgb_general.o
obj-$(CONFIG_AIC_PANEL_LVDS_GENERAL)	+= panel_lvds_general.o
obj-$(CONFIG_AIC_PANEL_DSI_B080XAN)	+= panel_dsi_b080xan.o
obj-$(CONFIG_AIC_PANEL_DSI_WUXGA_7IN)	+= panel_dsi_wuxga_7in.o
obj-$(CONFIG_AIC_PANEL_DSI_HX8394_5IN)	+= panel_dsi_hx8394_5in.o
obj-$(CONFIG_AIC_PANEL_DSI_ST7701S)	+= panel_dsi_st7701s.o
obj-$(CONFIG_AIC_PANEL_DSI_XM91080)	+= panel_dsi_xm91080.o
obj-$(CONFIG_AIC_PANEL_DSI_ILI9881C)	+= panel_dsi_ili9881c.o

obj-$(CONFIG_VIDEO_ARTINCHIP) 	+= panel_com.o
obj-$(CONFIG_AIC_DISP_MIPI_DSI) += panel_dsi.o
