TEST_PM_MBOX_VERSION =
TEST_PM_MBOX_ENABLE_TARBALL = NO
TEST_PM_MBOX_ENABLE_PATCH = NO

TEST_PM_MBOX_DEPENDENCIES += test-common
TEST_PM_MBOX_LIBS += -lpthread

TEST_PM_MBOX_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
