# SPDX-License-Identifier:	GPL-2.0

obj-y += userid.o
obj-$(CONFIG_USERID_IS_IN_SPINAND) += spinand.o spl_spinand.o
obj-$(CONFIG_USERID_IS_IN_SPINOR) += spinor.o
obj-$(CONFIG_USERID_IS_IN_MMC) += mmc.o
