TEST_LIBMAD_VERSION =
TEST_LIBMAD_ENABLE_TARBALL = NO
TEST_LIBMAD_ENABLE_PATCH = NO

TEST_LIBMAD_DEPENDENCIES += libmad alsa-lib

TEST_LIBMAD_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
