AIC_AUTHORIZATION_VERSION =
AIC_AUTHORIZATION_ENABLE_TARBALL = NO
AIC_AUTHORIZATION_ENABLE_PATCH = NO

AIC_AUTHORIZATION_DEPENDENCIES += libkcapi libopenssl test-common

AIC_AUTHORIZATION_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))

