# SPDX-License-Identifier: GPL-2.0
#
# Makefile for ArtInChip SoC clk
#

obj-$(CONFIG_$(SPL_TPL_)CLK_ARTINCHIP)	+= clk-artinchip.o
obj-$(CONFIG_$(SPL_TPL_)CLK_ARTINCHIP_CMU) += aic-cmu.o
obj-$(CONFIG_CLK_ARTINCHIP)	+= clk-cmd.o