# SPDX-License-Identifier: GPL-2.0
#
# Makefile for ArtInChip SoC clk
#

obj-$(CONFIG_$(SPL_TPL_)CLK_ARTINCHIP)	+= clk-artinchip.o
obj-$(CONFIG_$(SPL_TPL_)CLK_ARTINCHIP_CMU_V1_0) += aic-cmu.o
obj-$(CONFIG_$(SPL_TPL_)CLK_ARTINCHIP_CMU_V2_0) += aic-cmu-v20.o
obj-$(CONFIG_$(SPL_TPL_)CLK_ARTINCHIP_CMU_V3_0) += aic-cmu-v30.o
obj-$(CONFIG_CLK_ARTINCHIP)	+= clk-cmd.o