TEST_MTOP_VERSION =
TEST_MTOP_ENABLE_TARBALL = NO
TEST_MTOP_ENABLE_PATCH = NO

TEST_MTOP_DEPENDENCIES += test-common

TEST_MTOP_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
