# SPDX-License-Identifier: GPL-2.0
# Core
obj-$(CONFIG_PINCTRL_ARTINCHIP)	+= pinctrl-aic.o

# SoC Drivers
obj-$(CONFIG_PINCTRL_ARTINCHIP_V1)	+= pinctrl-aic-v1.o
obj-$(CONFIG_PINCTRL_ARTINCHIP_V0_1)	+= pinctrl-aic-v0.1.o
