TEST_BLKDEV_VERSION =
TEST_BLKDEV_ENABLE_TARBALL = NO
TEST_BLKDEV_ENABLE_PATCH = NO

TEST_BLKDEV_DEPENDENCIES += test-common

TEST_BLKDEV_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
