TEST_MBOX_VERSION =
TEST_MBOX_ENABLE_TARBALL = NO
TEST_MBOX_ENABLE_PATCH = NO

TEST_MBOX_DEPENDENCIES += test-common
TEST_MBOX_LIBS += -lpthread

TEST_MBOX_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
