#!/bin/sh
#
# Start qtlauncher....
#

export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export TSLIB_FBDEVICE=/dev/fb0
export POINTERCAL_CALIBFILE=/etc/pointercal
export TSLIB_CONSOLEDEVICE=none
export TSLIB_TSDEVICE=/dev/input/event0
export TSLIB_PLUGINDIR=/usr/lib/ts
export QWS_MOUSE_PROTO=tslib:/dev/input/event0

DAEMON="/usr/local/launcher/qtlauncher"
DAEMONOPTS=" -qws"
PIDFILE=/var/run/qtlauncher.pid

start() {
      printf "Starting qtlauncher: "
      PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
      if [ -z $PID ]; then
          printf "Fail \n"
      else
          echo $PID >$PIDFILE
          printf "OK \n"
      fi
}

stop() {
	printf "Stopping qtlauncher: "
        PID=`cat $PIDFILE`
        if [ -f $PIDFILE]; then
            kill -HUP $PID
            printf "OK \n"
            rm -f $PIDFILE
        else
            printf "pidfile not found \n"
        fi
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
