TEST_EFUSE_VERSION =
TEST_EFUSE_ENABLE_TARBALL = NO
TEST_EFUSE_ENABLE_PATCH = NO

TEST_EFUSE_DEPENDENCIES += test-common

TEST_EFUSE_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
