# SPDX-License-Identifier: GPL-2.0
obj-y					+= heap-helpers.o
obj-$(CONFIG_DMABUF_HEAPS_SYSTEM)	+= system_heap.o
obj-$(CONFIG_DMABUF_HEAPS_CMA)		+= cma_heap.o
obj-$(CONFIG_DMABUF_HEAPS_MPP)		+= mpp_heap.o
obj-$(CONFIG_MPP_DEBUGFS)		+= mpp_debugfs.o
