# SPDX-License-Identifier:	GPL-2.0

obj-y += d211.o
obj-y += env_location.o
obj-y += efuse_cmd.o
obj-$(CONFIG_AICUPG_ARTINCHIP) += usb_device_check.o
obj-$(CONFIG_UPDATE_UDISK_FATFS_ARTINCHIP) += usb_host_check.o
obj-$(CONFIG_$(SPL_TPL_)ENV_IS_IN_MMC) += mmc_env.o
