TEST_TOUCHSCREEN_VERSION =
TEST_TOUCHSCREEN_ENABLE_TARBALL = NO
TEST_TOUCHSCREEN_ENABLE_PATCH = NO

TEST_TOUCHSCREEN_DEPENDENCIES += tslib test-common

TEST_TOUCHSCREEN_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
