LVGL_UI_VERSION =
LVGL_UI_ENABLE_TARBALL = NO
LVGL_UI_ENABLE_PATCH = NO
LVGL_UI_INSTALL_STAGING = YES

LVGL_UI_DEPENDENCIES += aic-mpp
ifeq (${BR2_PACKAGE_TSLIB},y)
LVGL_UI_DEPENDENCIES += tslib
endif
ifeq (${BR2_PACKAGE_LIBDRM},y)
LVGL_UI_DEPENDENCIES += libdrm
endif
LVGL_UI_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
ifeq ($(BR2_TEST_LVGL_USE_RTP),y)
LVGL_UI_CONF_OPTS += -DUSE_RTP_TSLIB=yes
else
LVGL_UI_CONF_OPTS += -DUSE_RTP_TSLIB=no
endif

ifeq ($(BR2_LVGL_FB_DMA_NONCOHERENT),y)
LVGL_UI_CONF_OPTS += -DUSE_CACHE_FRAMEBUFFER=yes
else
LVGL_UI_CONF_OPTS += -DUSE_CACHE_FRAMEBUFFER=no
endif

ifeq ($(BR2_LVGL_DISPLAY_ROTATE_EN),y)
LVGL_UI_CONF_OPTS += -DLV_DISPLAY_ROTATE_EN=yes
else
LVGL_UI_CONF_OPTS += -DLV_DISPLAY_ROTATE_EN=no
endif

ifeq ($(BR2_LVGL_V_8),y)
LVGL_UI_CONF_OPTS += -DLVGL_V_8=yes
else
LVGL_UI_CONF_OPTS += -DLVGL_V_8=no
endif

ifeq ($(BR2_LVGL_V_9),y)
LVGL_UI_CONF_OPTS += -DLVGL_V_9=yes
else
LVGL_UI_CONF_OPTS += -DLVGL_V_9=no
endif

ifeq ($(BR2_LVGL_FBDEV),y)
LVGL_UI_CONF_OPTS += -DLVGL_FBDEV=yes
else
LVGL_UI_CONF_OPTS += -DLVGL_FBDEV=no
endif

ifeq ($(BR2_LVGL_DRM),y)
LVGL_UI_CONF_OPTS += -DLVGL_DRM=yes
else
LVGL_UI_CONF_OPTS += -DLVGL_DRM=no
endif

ifeq ($(BR2_LVGL_ROTATE_0),y)
LVGL_UI_CONF_OPTS += -DLV_ROTATE_DEGREE_0=yes
else
LVGL_UI_CONF_OPTS += -DLV_ROTATE_DEGREE_0=no
endif

ifeq ($(BR2_LVGL_ROTATE_90),y)
LVGL_UI_CONF_OPTS += -DLV_ROTATE_DEGREE_90=yes
else
LVGL_UI_CONF_OPTS += -DLV_ROTATE_DEGREE_90=no
endif

ifeq ($(BR2_LVGL_ROTATE_180),y)
LVGL_UI_CONF_OPTS += -DLV_ROTATE_DEGREE_180=yes
else
LVGL_UI_CONF_OPTS += -DLV_ROTATE_DEGREE_180=no
endif

ifeq ($(BR2_LVGL_ROTATE_270),y)
LVGL_UI_CONF_OPTS += -DLV_ROTATE_DEGREE_270=yes
else
LVGL_UI_CONF_OPTS += -DLV_ROTATE_DEGREE_270=no
endif

ifeq ($(BR2_PACKAGE_FREETYPE),y)
LVGL_UI_DEPENDENCIES += freetype
LVGL_UI_CONF_OPTS += -DUSE_FREETYPE=yes -DSTAGING_DIR=$(STAGING_DIR)
else
LVGL_UI_CONF_OPTS += -DUSE_FREETYPE=no
endif

ifeq ($(BR2_PACKAGE_AIC_MEM),y)
LVGL_UI_DEPENDENCIES += aic-mem
LVGL_UI_CONF_OPTS += -DUSE_AIC_MEM=yes
else
LVGL_UI_CONF_OPTS += -DUSE_AIC_MEM=no
endif

define LVGL_UI_POST_TARGET_INSTALL
	@$(call MESSAGE,"post target install")
	$(INSTALL) -m 0755 -D package/artinchip/lvgl-ui/S00lvgl \
		$(TARGET_DIR)/etc/init.d/S00lvgl
endef

LVGL_UI_POST_INSTALL_TARGET_HOOKS += LVGL_UI_POST_TARGET_INSTALL

ifeq ($(BR2_PACKAGE_LVGL_UI), y)
$(eval $(cmake-package))
endif
