LVGL_UI_VERSION =
LVGL_UI_ENABLE_TARBALL = NO
LVGL_UI_ENABLE_PATCH = NO
LVGL_UI_INSTALL_STAGING = YES

LVGL_UI_DEPENDENCIES += tslib
LVGL_UI_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
ifeq ($(BR2_TEST_LVGL_USE_RTP),y)
LVGL_UI_CONF_OPTS += -DUSE_RTP_TSLIB=yes
else
LVGL_UI_CONF_OPTS += -DUSE_RTP_TSLIB=no
endif

ifeq ($(BR2_PACKAGE_FREETYPE),y)
LVGL_UI_DEPENDENCIES += freetype
LVGL_UI_CONF_OPTS += -DUSE_FREETYPE=yes -DSTAGING_DIR=$(STAGING_DIR)
else
LVGL_UI_CONF_OPTS += -DUSE_FREETYPE=no
endif

define LVGL_UI_POST_TARGET_INSTALL
    @$(call MESSAGE,"post target install")
	$(INSTALL) -m 0755 -D package/artinchip/lvgl-ui/S00lvgl \
		$(TARGET_DIR)/etc/init.d/S00lvgl
endef

LVGL_UI_POST_INSTALL_TARGET_HOOKS += LVGL_UI_POST_TARGET_INSTALL

$(eval $(cmake-package))
