TEST_AUDIO_VERSION =
TEST_AUDIO_ENABLE_TARBALL = NO
TEST_AUDIO_ENABLE_PATCH = NO

TEST_AUDIO_DEPENDENCIES += alsa-lib test-common

TEST_AUDIO_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
$(eval $(cmake-package))
