LIBUSERID_VERSION =
LIBUSERID_ENABLE_TARBALL = NO
LIBUSERID_ENABLE_PATCH = NO
LIBUSERID_INSTALL_STAGING = YES

LIBUSERID_DEPENDENCIES += zlib libzlib
# LIBUSERID_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local
#
define LIBUSERID_REMOVE_HEADERS_IN_TARGET
	rm -rf $(TARGET_DIR)/usr/include/artinchip
endef
LIBUSERID_POST_INSTALL_TARGET_HOOKS += LIBUSERID_REMOVE_HEADERS_IN_TARGET
$(eval $(cmake-package))
