AICP_DEC_VERSION =
AICP_DEC_ENABLE_TARBALL = NO
AICP_DEC_ENABLE_PATCH = NO
AICP_DEC_INSTALL_STAGING = YES

AICP_DEC_DEPENDENCIES += aic-mpp
ifeq ("$(BR2_riscv)","y")
AICP_DEC_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local -DARCH=RISCV
endif
ifeq ("$(BR2_arm)","y")
AICP_DEC_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr/local -DARCH=ARM
endif

AICP_DEC_CONF_OPTS += -DGNU_TARGET_NAME=$(GNU_TARGET_NAME)

$(eval $(cmake-package))

